### ISSUE TITLE
Error when rendering buttons

### ISSUE THREAD

**Issue by d4mn** [paypal/paypal-smart-payment-buttons#12]
Server responds with 500 error when rendering buttons at this link

https://www.paypal.com/smart/buttons?style.label=paypal&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&components.0=buttons&locale.country=US&locale.lang=en&sdkMeta=******

sdkMeta params removed.

And responds with error: 

`Error: Expected host to be passed for sdk url
    at validateSDKUrl (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/@paypal/sdk-client/server/meta.js:104:11)
    at unpackSDKMeta (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/@paypal/sdk-client/server/meta.js:185:5)
    at buttonMiddleware (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/@paypal/smart-payment-buttons/server/button.js:31:40)
    at Layer.handle [as handle_request] (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:317:13)
    at /dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:335:12)
    at next (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:275:10)
    at /dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/auth-paypal/lib/index.js:123:17
    at validate (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/st-validation-paypal/lib/index.js:40:13)
    at /dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/auth-paypal/lib/index.js:80:13
    at initialize (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/passport/lib/middleware/initialize.js:62:5)
    at initializeauth (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/auth-paypal/lib/index.js:66:9)
    at Layer.handle [as handle_request] (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:317:13)
    at /dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:335:12)
    at next (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/express/lib/router/index.js:275:10)
    at /dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/hermes-at-authorize/lib/index.js:54:13
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at tryCatcher (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/bluebird/js/main/async.js:15:14)
    at Immediate.<anonymous> (/dependencies/smartcomponentnodeweb/cronus/scripts/node_modules/async-listener/glue.js:188:31)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)`

Is it server side error or client side can't figure it out ;/

**Comment by bluepnume** [comment]
Are you actually passing `sdkMeta=******`? (FYI -- if you still see a problem, please raise an issue over at https://github.com/paypal/paypal-checkout-components)
